services:
  angular-challenge:
    container_name: angular-challenge
    build: .
    ports:
      - "4200:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      TZ: ${TIMEZONE:-Asia/Kuala_Lumpur}
networks:
  default:
    name: nginx-proxy
    external: true