services:
  app:
    container_name: angular-challenge
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    ports:
      - "4200:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
